name: movie_app2
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.8.1
  firebase_auth: ^5.3.4
  video_player: ^2.9.2
  font_awesome_flutter: ^10.1.0
  http: ^1.2.2
  youtube_player_flutter: ^8.0.0
  webview_flutter: ^3.0.0
  flutter_inappwebview: ^5.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  # youtube_player_flutter: ^8.1.2
  flutter_webview_plugin: ^0.4.0

flutter:
  uses-material-design: true
  assets:
    - assets/data/movie.json

